### PR TITLE
Add AddressPool validation check for invalid ranges where first address of the range is after the second

### PR DESCRIPTION
**Pull request by sabinaaledort**
An AddressPool where the first address of the range is after the second
should be an invalid range. In such case the LoadBalancer service is
unable to get an IP.

The service is not getting an ip with the following error:
`{"caller":"level.go:63","error":"no available IPs","level":"error","msg":"IP allocation failed","op":"allocateIP","service":"default/nginx","ts":"2021-09-13T08:40:02.487727369Z"}`

```
$ kubectl get service -A
NAMESPACE     NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       nginx        LoadBalancer   10.96.240.166   <pending>     80:32319/TCP             53s
```

### CODE REVIEW

**Comment by fedepaol** [comment]
Looks good to me

**Comment by russellb** [comment]
This looks like a good candidate for a simple unit test.  Thanks!

**Comment by rata** [comment]
@sabinaaledort thanks! It mostly LGTM, but can you fix the CI issue (from [here][link] it seems the issue is that "body must have leading blank line [body-leading-blank]")? A unit test like russell mentioned would be nice


[link]: https://github.com/metallb/metallb/pull/948/checks?check_run_id=3614544299

**Comment by russellb** [comment]
Thank you for adding the test!

**Pull request merged**
