### PR TITLE
Helm: Add optional annotations for podMonitors and prometheusRules

### PR DESCRIPTION
**Pull request by sathieu**
My particular use case is adding the following annotation:

```
argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
```

Ref: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types

### CODE REVIEW

**Comment by fedepaol** [comment]
cc @gclawes 

@sathieu mind checking the CI failures?

**Comment by sathieu** [comment]
@fedepaol I don't understand the failures, but I reworked the code. I need that someone unlock the CI.

**Comment by sathieu** [comment]
@fedepaol I don't understand the [CI failure](https://github.com/metallb/metallb/runs/6807971717?check_suite_focus=true):

> ```
> Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/metallb/metallb/metallb'. No such file or directory
> ```

**Comment by fedepaol** [comment]
> @fedepaol I don't understand the [CI failure](https://github.com/metallb/metallb/runs/6807971717?check_suite_focus=true):
> 
> > ```
> > Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/metallb/metallb/metallb'. No such file or directory
> > ```

oh, the use-operator lane was broken for other reasons (waiting for https://github.com/metallb/metallb-operator/pull/206 to be merged) but this may be some other thing, let me fix it.
Your PR doesn't have anything to do with that.

**Comment by sathieu** [comment]
@fedepaol I've rebased on top of main.

**Comment by gclawes** [comment]
The diff looks good to me.  @fedepaol are we still waiting on a fix for the operator related CI failures?

**Comment by sathieu** [comment]
thanks for merging :pray:

**Pull request merged**
