### PR TITLE
Update kind to v0.9.0

### PR DESCRIPTION
**Pull request by johananl**
This PR updates kind to the current latest version - `v0.9.0` which also uses k8s `v1.19` by default.

### CODE REVIEW

**Comment by johananl** [comment]
This breaks `inv dev-env`. Fixing.

**Comment by aojea** [comment]
great :clap:

**Review by daxmc99 — APPROVED** [review]
LGTM! 👍

**Comment by russellb** [comment]
related old PR: https://github.com/metallb/metallb/pull/715/

ideally would merge that first and include an update to the version validation here

**Comment by johananl** [comment]
Right, thanks @russellb and thanks @daxmc99 for merging #715.

**Pull request merged**
