### PR TITLE
Make the name of the webhook certs more metallb specific

### PR DESCRIPTION
**Pull request by cyclinder**
Rename webhook_service/webhook_cert name to avoid name conflicts with other resources in the cluster.

Fixes https://github.com/metallb/metallb/issues/2174

### CODE REVIEW

**Comment by fedepaol** [comment]
@cyclinder mind checking the CI failures? I guess something went wrong.
Thanks!

**Comment by cyclinder** [comment]
sure, let me checking these failures

**Comment by cyclinder** [comment]
Hi @fedepaol, If we update the names of webhook_service/webhook_cert directly, this may be an incompatible change, which leads to failures with [metallb-operator](https://github.com/metallb/metallb/actions/runs/7724726313/job/21071331380?pr=2244) (the old manifests use the new docker-image, and the correct name is not specified in the controller via go flags). I think there are two ways:

1. Update metallb-operator to make it compatible with this change
2. Close this PR, webhook_service/webhook_cert are already configured.

I think 2 is enough, but I prefer 1, I like the default value to be metallb related.

**Comment by DrBu7cher** [comment]
Can you fix https://github.com/metallb/metallb/blob/main/charts/metallb/charts/crds/templates/crds.yaml#L260 before everything else?
Because we see a lot of
```
cacher (bgppeers.metallb.io): unexpected ListAndWatch error: failed to list metallb.io/v1beta1, Kind=BGPPeer: conversion webhook for metallb.io/v1beta2, Kind=BGPPeer failed: Post "https://webhook-service.metallb.svc:443/convert?timeout=30s": service "webhook-service" not found; reinitializing...
```
in out api-server.

It was introduced here https://github.com/metallb/metallb/commit/5339a9a9d3742ff168a71358cc36ce4a702ed19d I think. Since the service was renamed from `metallb-webhook-service` to `webhook-service`.

**Comment by fedepaol** [comment]
@cyclinder mind fixing the conflicts?

**Comment by fedepaol** [comment]
Just a nit on the commit / PR title: here we are not making the name configurable, but fixing it to a metallb-only value.

**Comment by fedepaol** [comment]
LGTM

**Pull request merged**
