### PR TITLE
Add repo LICENSE file to docker container images

### PR DESCRIPTION
**Pull request by alexmasi**
Adding the repo LICENSE file to the produced docker container images

### CODE REVIEW

**Comment by jtcarnes** [comment]
Generally not unless it's something custom. I would generally suggest adding the open OCI annotation to the image about the license. I have a different MR that should add the license annotation once merged.

**Comment by fedepaol** [comment]
> @fedepaol on further reflection, it depends. Some security auditors want all the licenses in the container for easier scanning with tools. (I've worked with some that all they knew was how to use the tool).
> 
> It's not a huge change and can help some of the enterprise users in security auditing. (the label should be enough but not all security folks are... up to speed on containers).
> 
> I can add it to #1414 if you want as it's reworking the dockerfile anyway.

Fair enough. @jtcarnes I'd keep it in this PR to give credit to the author. Let me fix it.

**Comment by fedepaol** [comment]
@alexmasi apologies, I tried to force push to your branch but I think I messed up with the fact that you filed a pr from main instead of a branch (I think). gh won't allow me to push to your main branch anymore, so I can't add the missing commit.
If you are still interested please reopen it.

**Comment by alexmasi** [comment]
Looks like https://github.com/metallb/metallb/pull/1414 will add the licenses files, so if that is still planning on being merged then I'm all set.

**Comment by fedepaol** [comment]
cool, thanks. And sorry again!

**Pull request closed without merging**
