### PR TITLE
speaker: Added preferred L2 speaker node feature

### PR DESCRIPTION
**Pull request by apolovov**
## Description
The new Service annotation `metallb.universe.tf/preferredL2SpeakerNode` to force L2-announcing from specific Node if it is alive.

## Why do we need it, and what problem does it solve?
Related to https://github.com/metallb/metallb/issues/439.
For now, speakers in Layer2 mode are announcing only a single External IP per Service. This IP is being announced by a single Node, which is elected by hashing algorithm. So, unlike BGP mode, I can't load all front nodes. But i need.
@fedepaol [offered a solution](https://github.com/metallb/metallb/issues/439#issuecomment-1271664497) to use multiple Services sharing the same set of endpoints. This would work if I was confident that the announcements would be evenly distributed across all front-end nodes, but the nodes for services are selected independently of each other.
The solution in this PR is to add an annotation to specify preferred Node for announcing, if the node is dead, the election will happen as before. So that i can create multiple Services and pin them to frontend nodes manually.

## P.S.
This PR is proposal draft, if it has a right to live, I'll finish it (tests, docs, etc).

### CODE REVIEW

**Comment by fedepaol** [comment]
let me think about this a bit. If the feature makes sense, I'd rather have it specified by the L2Advertisement rather than an annotation.

**Comment by apolovov** [comment]
If we could pick the availableNode for current Service based on neighbouring Services (not just the first one), it could be solution.
For example, to index all the Services in order (0, 1, 2, 3...) and pick the active node with `availableNodes[serviceIndex % len(availableNodes)]`. So we'll evenly distribute IPs across the nodes without changing UX.

**Comment by fedepaol** [comment]
> If we could pick the availableNode for current Service based on neighbouring Services (not just the first one), it could be solution. For example, to index all the Services in order (0, 1, 2, 3...) and pick the active node with `availableNodes[serviceIndex % len(availableNodes)]`. So we'll evenly distribute IPs across the nodes without changing UX.

I think it's a bit more complex than this. We should filter out only the services that can be announced on the nodes the service can be announced from (which includes node selectors, endpoints in case of etp local) and given the dynamic nature, this can result in a service bouncing.
Even without this and considering your example, removing a service from the list would result in rearranging all the announcing nodes.

**Comment by fedepaol** [comment]
Hi! I know this may solve your short term problem, but I really want to think about this in a more broader term and see if we can do something better to improve the distribution of the L2 allocations across the cluster.
For this reason I am gonna close this PR, and will probably raise an issue to track these considerations. Thanks for the time spent here!

**Comment by nabokihms** [comment]
@fedepaol, any news about the issue? The solution is required to prevent reallocations of IP addresses, and living with the patch differs from what we would like to stick with.

**Pull request closed without merging**
