### PR TITLE
dev-env: Add missing parts to support dual stack

### PR DESCRIPTION
**Pull request by qinqon**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
/kind bug

**What this PR does / why we need it**:
Add missing parts to support dual stack at dev-env

**Special notes for your reviewer**:
It also formats task.py with "black", proper integration at PR:
- https://github.com/metallb/metallb/pull/2524

```release-note
Add missing parts to support dual stack at dev-env
```

### CODE REVIEW

**Comment by fedepaol** [comment]
tested locally, lgtm

**Comment by qinqon** [comment]
> tested locally, lgtm



> tested locally, lgtm

We will ping this PR when ovn-k is ready to take this.

**Comment by qinqon** [comment]
@fedepaol ovn-k is ready we can merge this, then we will have to create a metallb release to bump metallb at ovn-k with these changes.

**Comment by fedepaol** [comment]
LGTM, sending to merge queue

**Pull request merged**
