### PR TITLE
Add controller liveness and readiness probe

### LINKED ISSUE #952: Absence of endpoints for health checks in controller and workers
I didn't see in source code any traces of endpoints for health checks. It usually used by liveness and readiness checks in k8s.
Is this decision made on purpose or this part not implemented yet?

### PR DESCRIPTION
**Pull request by mgeri**
As in the Helm chart, we use the Prometheus endpoint for controller liveness and readiness probes on the k8s manifest.
The liveness and readiness probes parameters are aligned to the Helm chart defaults.

Fixed #952

### CODE REVIEW

**Comment by russellb** [comment]
It looks like helm sets these for both the controller and speaker. Would you like to add it to the speaker, as well?

**Comment by fedepaol** [comment]
@oribon we may want to refresh the operator after this.

**Comment by mgeri** [comment]
> It looks like helm sets these for both the controller and speaker. Would you like to add it to the speaker, as well?

Sure! I missed it when I looked at Helm's charts. Done.

**Comment by fedepaol** [comment]
Thanks!

**Pull request merged**
