### PR TITLE
Fix create secret snippet

### LINKED ISSUE #550: Description of secret creation is not correct.
Hi, I've noticed minor issue that the description of [secret creation](https://github.com/metallb/metallb/blame/main/website/content/installation/_index.md#L50) is not correct. It generates secret with '-' at least on mac.
Maybe it can be replaced with something more universal 
`openssl rand -base64 128 | xargs -0 -I {} kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="{}"`

### PR DESCRIPTION
**Pull request by olegmayko**
This should fix #550.

### CODE REVIEW

**Comment by champtar** [comment]
@olegmayko can you use my version so we don't require xargs ?

**Comment by olegmayko** [comment]
done

**Comment by champtar** [comment]
Thanks @olegmayko 
@rata @danderson please merge

**Comment by champtar** [comment]
I see it's in https://github.com/metallb/metallb/tree/v0.9, @rata can you cherry-pick it to main ?

**Comment by rata** [comment]
Ups, yeah, noticed. Will cherry-pick :man_facepalming: sorry :-)

**Comment by champtar** [comment]
It's good to have it in both branch

**Comment by rata** [comment]
Sorry, forgot to update that already did this, thanks again! :)

**Pull request merged**
