### PR TITLE
website: Update dependencies

### PR DESCRIPTION
**Pull request by johananl**

### CODE REVIEW

**Comment by russellb** [comment]
Did you do this in response to github flagging our `socket.io` dependency as being outdated and vulnerable to a CVE?  I was just looking at that.

Also, were you able to test this?  Or should we just push it live and roll back if the web site seems broken?

**Comment by johananl** [comment]
> Did you do this in response to github flagging our `socket.io` dependency as being outdated and vulnerable to a CVE? I was just looking at that.

Yes, that was the main reason.

> Also, were you able to test this? Or should we just push it live and roll back if the web site seems broken?

I've rendered the website locally using Hugo and couldn't find anything that was broken. No errors in the console either.

**Comment by russellb** [comment]
@johananl pretty harmless change, lgtm, merge whenever you're ready

**Comment by russellb** [comment]
Actually, I'll merge this now since it doesn't go live automatically.  We'll check it out on the netlify preview before we push the latest website changes live.

**Pull request merged**
