### PR TITLE
FRR: Allow nexthop tracking to resolve via the default route

### PR DESCRIPTION
**Pull request by oribon**
The native implementation could use the default route to peer with
routers outside its network that couldn't be reached otherwise.
We should enable it in FRR as well to support peering with these routers.
https://docs.frrouting.org/en/latest/zebra.html#clicmd-ip-nht-resolve-via-default

Signed-off-by: Ori Braunshtein <obraunsh@redhat.com>

### CODE REVIEW

**Comment by msherif1234** [comment]
This is only need for eBGP multi-hop case right ? I don't think its right to unconditionally resolve over default route in other cases ?

**Comment by fedepaol** [comment]
> This is only need for eBGP multi-hop case right ? I don't think its right to unconditionally resolve over default route in other cases ?

I am pretty ignorant here but I think this is a fallback when we don't have explicit routes to reach the neighbor? Also, why would it be limited to eBGP? Can't we have iBGP but multi-hopped (although probably not that common)?

**Comment by msherif1234** [comment]
> > This is only need for eBGP multi-hop case right ? I don't think its right to unconditionally resolve over default route in other cases ?
> 
> I am pretty ignorant here but I think this is a fallback when we don't have explicit routes to reach the neighbor? Also, why would it be limited to eBGP? Can't we have iBGP but multi-hopped (although probably not that common)?

eBGP is the only type "by default" assumes only one hop and send NEXT_HOP in the update messages to peers unlike iBGP so we don't endup with routing loop.

can we get FRR folks eye on this PR

**Comment by cgoncalves** [comment]
> This is only need for eBGP multi-hop case right ? I don't think its right to unconditionally resolve over default route in other cases ?

Not necessarily. Consider a spine-leaf network architecture where the worker nodes (rack servers) need to iBGP peer with the spine switches or datacenter routers but they do not have a specific route in their RIB hence can only be resolved via the default route.

**Comment by msherif1234** [comment]
> > This is only need for eBGP multi-hop case right ? I don't think its right to unconditionally resolve over default route in other cases ?
> 
> Not necessarily. Consider a spine-leaf network architecture where the worker nodes (rack servers) need to iBGP peer with the spine switches or datacenter routers but they do not have a specific route in their RIB hence can only be resolved via the default route.

I thought this works only for passive nbr ?

**Comment by msherif1234** [comment]
> > > This is only need for eBGP multi-hop case right ? I don't think its right to unconditionally resolve over default route in other cases ?
> > 
> > 
> > Not necessarily. Consider a spine-leaf network architecture where the worker nodes (rack servers) need to iBGP peer with the spine switches or datacenter routers but they do not have a specific route in their RIB hence can only be resolved via the default route.
> 
> I thought this works only for passive nbr ?

I doubled checked with frr folks and they think it safe to go with

**Comment by fedepaol** [comment]
So are we all good with this?

**Comment by fedepaol** [comment]
LGTM

**Pull request merged**
