### PR TITLE
Update Usage Docs For Clarifying Example

### PR DESCRIPTION
**Pull request by mitchross**
Update documentation to include an example for metallb.universe.tf/loadBalancerIPs

### CODE REVIEW

**Comment by liornoy** [comment]
Nice and helpful addition.

**Comment by dehylton** [comment]
Omitting this from the documentation is unfortunate.

**Comment by mitchross** [comment]
> Omitting this from the documentation is unfortunate. Thank you for the example.

Check my repo for more examples !

**Comment by fedepaol** [comment]
Apologies for letting this fall back. Will merge it, thanks for the contribution!

**Pull request merged**
