### PR TITLE
Bump controller-runtime, the kubernetes deps and the kind version

### PR DESCRIPTION
**Pull request by fedepaol**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind cleanup
> /kind feature
> /kind design
> /kind flake
> /kind failing
> /kind documentation
> /kind regression

**What this PR does / why we need it**:

Consuming the latest kubernetes libraries. Also, bumping the version of kind (and thus, of kubernetes) that we run our CI against.

**Special notes for your reviewer**:

The cert-controller is pinned using a pseudoversion. This is because of a compatibility skew of the controller-runtime library (see https://github.com/open-policy-agent/cert-controller/issues/207)

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fedepaol** [comment]
Fixes https://github.com/metallb/metallb/issues/2426
Fixes https://github.com/metallb/metallb/issues/2416

**Comment by karampok** [comment]
The go.mod file inside the e2etest workspace should also be aligned, otherwise when running the e2e test will have a such error
```
go: module .. listed in go.work file requires go >= 1.22, but go.work lists go 1.21; to update it:
	go work use
```

**Comment by fedepaol** [comment]
> The go.mod file inside the e2etest workspace should also be aligned, otherwise when running the e2e test will have a such error
> 
> ```
> go: module .. listed in go.work file requires go >= 1.22, but go.work lists go 1.21; to update it:
> 	go work use
> ```

right! And I also need to bump the deps there!

**Review by oribon — APPROVED** [review]
lgtm

**Pull request merged**
