### PR TITLE
Add runtimeClassName support to speaker template

### PR DESCRIPTION
**Pull request by jlclx**
Modifies template to add runtimeClassName variable interpolation.

### CODE REVIEW

**Comment by champtar** [comment]
You need to also edit the 'values' file

**Comment by jlclx** [comment]
Thank you.
Is this correct?

**Comment by fedepaol** [comment]
@jlclx mind extending the commit message explaining the rationale of this change?
What's described in https://github.com/metallb/metallb/issues/945 is a pretty clear explanation of why we need this change.

**Comment by jlclx** [comment]
Is this an acceptable extension to the commit message?

**Comment by fedepaol** [comment]
> Is this an acceptable extension to the commit message?

looks great, thanks!

**Comment by russellb** [comment]
seems fine to me, but I don't know helm.  @gclawes can you take a look and ack this?  thank you

**Comment by gclawes** [comment]
`values.schema.json` would also need an update for validation of the new field.

**Comment by jlclx** [comment]
Thank you for informing me I missed something.
I believe this should resolve it.

**Review by rata — APPROVED** [review]
LGTM, but would like @gclawes to confirm :)

**Comment by gclawes** [comment]
LGTM.

**Comment by russellb** [comment]
I updated the commit to fix the commit-lint issue (wrap commit message at 72 characters)

**Pull request merged**
