### PR TITLE
Tests: Use the ipfamily type instead of strings

### PR DESCRIPTION
**Pull request by fedepaol**
During the dual stack implementation, an "ipfamily" type was introduced.
E2e tests kept using the strings, here we align them to use the type,
enforcing the values.

### CODE REVIEW

**Comment by oribon** [comment]
lgtm

**Comment by oribon** [comment]
should you also change https://github.com/metallb/metallb/blob/123d6cd692e41e1a0637c3a28c29278fcdce5a2e/e2etest/layer2_test.go#L356 ?

**Comment by fedepaol** [comment]
> should you also change
> 
> https://github.com/metallb/metallb/blob/123d6cd692e41e1a0637c3a28c29278fcdce5a2e/e2etest/layer2_test.go#L356
> ?

good point, I missed it

**Comment by msherif1234** [comment]
LGTM

**Pull request merged**
