### PR TITLE
go.mod: use k8s.io/client-go@v0.20.2

### LINKED ISSUE #722: go.mod: an unspecified version of the k8s api is used
In `go.mod` the k8s.io/api version is unspecified which normally means something like "what happens to be the case when go.mod was updated";
```
module go.universe.tf/metallb

go 1.12

require (
...
        k8s.io/api v0.0.0-20190620084959-7cf5895f2711
        k8s.io/apimachinery v0.0.0-20190612205821-1799e75a0719
        k8s.io/client-go v0.0.0-20190620085101-78d2af792bab
        k8s.io/klog v0.3.1
)
```
While this usually works it is not very good for maintenance.

As an example metallb can't be built with the current k8s.io/api (v0.19.0). I bumbed immediately into this while working on new features in the controller for https://github.com/metallb/metallb/issues/698.

To select a k8s.io/api version do;
```
go get k8s.io/client-go@v0.19.0
go mod tidy
```
For available versions please see;
https://github.com/kubernetes/client-go#compatibility-matrix

### PR DESCRIPTION
**Pull request by invidian**
Use a defined version of k8s.io/client-go.

Fixes #722

Replaces #723, it should have CI passing.

Signed-off-by: Lars Ekman <lars.g.ekman@est.tech>

### CODE REVIEW

**Comment by rata** [comment]
@invidian @uablrek Thanks, I'm coming back online soon, I'll look into this to fix 1.20 when I'm back. @daxmc99 if you can review and probably release metallb before, it would be great!

@invidian @uablrek Just curious, when doing this change did you happen to see why it is broken now? I mean, was there some way for controllers using client-go < 1.20 to not be broken when 1.20 was released?

**Comment by invidian** [comment]
>@invidian @uablrek Just curious, when doing this change did you happen to see why it is broken now? I mean, was there some way for controllers using client-go < 1.20 to not be broken when 1.20 was released?

I'm sorry. It's unclear for me what you ask about. Did you mean why the update of K8s libraries is needed? If so, I should've mention it in commit message/PR description. It's actually to fix #794.

**Comment by ryancurrah** [comment]
Is there anything else missing? Would be nice to get this resolved.

**Comment by rata** [comment]
@ryancurrah No, sorry for the delay!

**Pull request closed without merging**
