### PR TITLE
Update speaker.yaml

### PR DESCRIPTION
**Pull request by NorthFuture**
wrong value reference

### CODE REVIEW

**Comment by russellb** [comment]
@gclawes can you take a look at this one?

**Comment by gclawes** [comment]
A similar change is needed for the controller: https://github.com/metallb/metallb/blob/main/charts/metallb/templates/controller.yaml#L22

@NorthFuture could you submit that?  Otherwise I can open a separate PR.

**Comment by russellb** [comment]
@gclawes I added a commit to this PR for the controller fix.  PR look good to you?

**Comment by gclawes** [comment]
Looks good to me.

**Pull request merged**
