### PR TITLE
CI: Re-enable L2ServiceStatus e2es

### PR DESCRIPTION
**Pull request by oribon**
The linked issue was closed, so we can re-enable the e2es.

**Is this a BUG FIX or a FEATURE ?**:

/kind cleanup

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fedepaol** [comment]
LGTM

**Comment by oribon** [comment]
@mquhuy hey, there seems to be a flake in one of the prefer ds tests [(https://github.com/metallb/metallb/actions/runs/12119306494?pr=2620)](https://github.com/metallb/metallb/actions/runs/12119306494/job/33785812149?pr=2620), do you have bandwidth to check it? the logs of the test are stored in the job's artifacts [kind-logs-dual-frr-k8s-external-helm](https://github.com/metallb/metallb/actions/runs/12119306494/artifacts/2261832878)

**Comment by mquhuy** [comment]
> @mquhuy hey, there seems to be a flake in one of the prefer ds tests [(https://github.com/metallb/metallb/actions/runs/12119306494?pr=2620)](https://github.com/metallb/metallb/actions/runs/12119306494/job/33785812149?pr=2620), do you have bandwidth to check it? the logs of the test are stored in the job's artifacts [kind-logs-dual-frr-k8s-external-helm](https://github.com/metallb/metallb/actions/runs/12119306494/artifacts/2261832878)

Sure. I can have a look

**Comment by mquhuy** [comment]
Hi @oribon. I found some problems with this test case and made a PR to fix it. Could you please have a look? https://github.com/metallb/metallb/pull/2624

**Comment by lwabish** [comment]
> @lwabish hey :) we forgot to enable the ci for the feature you wrote back then, and it seems there is a flake there (the merge queue failed), do you have bandwidth to check it?

Sure. Maybe need some time to reload my memory of this feature.

**Comment by fedepaol** [comment]
I am going to merge this despite the flake as having CI is always good. Please @oribon provide a link to the failure so whoever address it can find it.

**Comment by oribon** [comment]
@lwabish it doesn't always show up, it did in the merge queue in this pr https://github.com/metallb/metallb/actions/runs/12279509889/job/34263957180 , I don't remember we did anything to fix this

**Pull request merged**
