### PR TITLE
helm chart: fix wrong indentation in serviceMonitor.yaml

### PR DESCRIPTION
**Pull request by cyclinder**
helm chart: fix wrong indentation in serviceMonitor.yaml

### CODE REVIEW

**Comment by liornoy** [comment]
@cyclinder thanks for the fix.
It looks like we hit flakes from the recent NetowrkUnavailable condition feature.
I opened #1904 to investigate.

**Comment by oribon** [comment]
thanks for opening this :smile: 
are you maybe familiar with ways to avoid this kind of mis-indentations in the future? I (wrongly) assumed the helm lint already takes care of it
other than that, lgtm

**Comment by cyclinder** [comment]
I think there is no better way to check this, it's a bit tricky

**Comment by fedepaol** [comment]
What I don't understand is, we have running CI with prometheus and helm, and we validate the metrics on prometheus here https://github.com/metallb/metallb/blob/main/tasks.py#L376 .
So is this really preventing service monitors to work or is it cosmetics?

**Comment by cyclinder** [comment]
@fedepaol  In fact it does not prevent the creation of servicemonitor, it works.

**Comment by cyclinder** [comment]
unit test flaky due to data race: https://github.com/metallb/metallb/actions/runs/4878692038/jobs/8704569708?pr=1903

**Comment by cyclinder** [comment]
Hi @fedepaol， Do we still need this PR?

**Comment by fedepaol** [comment]
> Hi @fedepaol， Do we still need this PR?

yep, sorry. I thought I send it to the merge queue but it's clear I didn't

**Comment by cyclinder** [comment]
failed to merge due to failed status checks：https://github.com/metallb/metallb/actions/runs/4934324634/jobs/8819383473

**Comment by fedepaol** [comment]
let's try again

**Comment by cyclinder** [comment]
🤔

```shell
Run sudo apt-get update
Get:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3611 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
Get:[5](https://github.com/metallb/metallb/actions/runs/4936076777/jobs/8823372086#step:3:6) http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd[6](https://github.com/metallb/metallb/actions/runs/4936076777/jobs/8823372086#step:3:7)4 Packages [64.4 kB]
Get:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [7155 B]
Get:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [13.7 kB]
Get:9 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main all Packages [904 B]
Get:10 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [[7](https://github.com/metallb/metallb/actions/runs/4936076777/jobs/8823372086#step:3:8)04 kB]
Hit:11 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [1[8](https://github.com/metallb/metallb/actions/runs/4936076777/jobs/8823372086#step:3:9)5 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [14.4 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [483 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [78.1 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [8[9](https://github.com/metallb/metallb/actions/runs/4936076777/jobs/8823372086#step:3:10)0 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [182 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [18.7 kB]
Get:19 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [41.8 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [9408 B]
Get:21 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [471 kB]
Get:22 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [123 kB]
Get:23 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 c-n-f Metadata [9504 B]
Get:24 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [459 kB]
Get:25 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [74.1 kB]
Get:26 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [708 kB]
Get:27 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [121 kB]
Get:28 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [14.3 kB]
Get:29 http://azure.archive.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [26.6 kB]
Get:30 http://azure.archive.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [4996 B]
Fetched 5045 kB in 1s (4203 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-modules-extra-5.15.0-[10](https://github.com/metallb/metallb/actions/runs/4936076777/jobs/8823372086#step:3:11)36-azure
E: Couldn't find any package by glob 'linux-modules-extra-5.[15](https://github.com/metallb/metallb/actions/runs/4936076777/jobs/8823372086#step:3:16).0-10[36](https://github.com/metallb/metallb/actions/runs/4936076777/jobs/8823372086#step:3:37)-azure'
E: Couldn't find any package by regex 'linux-modules-extra-5.15.0-1036-azure'
```

It seems that the github CI environment is not very stable

**Comment by fedepaol** [comment]
> It seems that the github CI environment is not very stable

might be related to the issues of these days...

**Comment by fedepaol** [comment]
But https://www.githubstatus.com/ shows all green

**Pull request merged**
