### PR TITLE
Set BGP origin code into igp

### LINKED ISSUE #1217: Set BGP origin code (igp)
I've noticed that when looking at routes received by my router (pfSense FRR) the origin indicates a ? which means incomplete.  Could the origin flag be set?  For example, on a Cisco router you would setup a route-map and set origin to igp:

```
route-map azure_out permit 10
 set origin igp
```

This is the bgp table from my router.  In my case, 192.168.13.0/24 is being advertised by metallb in my cluster and we see a ? at the end of each line.

```
BGP table version is 10, local router ID is 192.168.0.1, vrf id 0
Default local pref 500, local AS 65500
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*> 192.168.0.0/24   0.0.0.0                  0         32768 i
*  192.168.3.0/24   192.168.26.9                           0 65505 65503 i
*>                  192.168.25.6             0             0 65503 i
*= 192.168.13.0/24  192.168.0.67                           0 65513 ?
*=                  192.168.0.66                           0 65513 ?
*=                  192.168.0.85                           0 65513 ?
*>                  192.168.0.68                           0 65513 ?
*= 192.168.13.1/32  192.168.0.67                           0 65513 ?
*=                  192.168.0.66                           0 65513 ?
*=                  192.168.0.85                           0 65513 ?
*>                  192.168.0.68                           0 65513 ?
*= 192.168.13.2/32  192.168.0.67                           0 65513 ?
*=                  192.168.0.66                           0 65513 ?
*=                  192.168.0.85                           0 65513 ?
*>                  192.168.0.68                           0 65513 ?
*> 192.168.65.0/24  192.168.26.9             0             0 65505 i
*> 192.168.67.0/24  192.168.26.9                           0 65505 65506 i
```

### PR DESCRIPTION
**Pull request by pperiyasamy**
Currently BGP origin code for external IP routes advertised
by metallb is set to `incomplete` which is incorrect.

Hence setting this value to `igp` by default which seems to be
appropriate origin code for service routes.

Fixes #1217

Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>

### CODE REVIEW

**Comment by fedepaol** [comment]
Is this something we can extend the current tests to validate it?

**Comment by pperiyasamy** [comment]
> Is this something we can extend the current tests to validate it?

yes @fedepaol , added a validation to check bgp origin now.

**Comment by fedepaol** [comment]
LGTM

**Pull request merged**
