### PR TITLE
Change the FRR image to quay.io/frrouting/frr:7.5.1

### LINKED ISSUE #1779: Image quay.io/frrouting/frr:stable_7.5 was removed causing metallb v0.12 to fail
Looking at [this](https://github.com/metallb/metallb-operator/pull/297) metallb-operator PR CI fail on the backward compatibility lane, it seems that the frr:stable_7.5 image was removed from quay.io which means, metallb v0.12 users can not deploy the FRR containers.
The available quay.io frrouting frr images: https://quay.io/repository/frrouting/frr?tab=tags

### PR DESCRIPTION
**Pull request by liornoy**
**NOTE: this PR is for metallb:v0.12**

This PR changes the frr image from quay.io/frrouting/frr:stable_7.5 to
quay.io/frrouting/frr:7.5.1, as image stable_7.5 was removed.
    
fix #1779

### CODE REVIEW

**Comment by cgoncalves** [comment]
This PR is, in fact, downgrading FRR to 7.5.1 from stable_7.5 as well as changing to Docker Hub from Quay.io and the justification for it is in the linked issue https://github.com/metallb/metallb/issues/1779. This is a temporary change, it seems. Perhaps it would be better to leave a NOTE type message in the code so we don't forget so easily.

On a related note, I think it is time to upgrade FRR to version 8.x. @fedepaol what do you think?

**Comment by fedepaol** [comment]
> This PR is, in fact, downgrading FRR to 7.5.1 from stable_7.5 as well as changing to Docker Hub from Quay.io and the justification for it is in the linked issue #1779. This is a temporary change, it seems. Perhaps it would be better to leave a NOTE type message in the code so we don't forget so easily.
> 

Please note this is against the 0.12 branch. Subsequent branches are already back to dockerhub. The frr maintainers told us that the quay mirror was sort of an experiment, but it makes sense not to break metallb for those users willing to consume 0.12

> On a related note, I think it is time to upgrade FRR to version 8.x. @fedepaol what do you think?


Yep, I even filed an issue a while ago: https://github.com/metallb/metallb/issues/17534

**Comment by cgoncalves** [comment]
Sorry, missed that this PR was not against the main branch.
LGTM

**Comment by fedepaol** [comment]
frr is moving to quay, so we should reconsider this. 
See https://frrouting.slack.com/archives/C4T714TAQ/p1673628274809459

We are currently in the process of building and pushing old releases to Quay. Once that's done, the copy on the webpage I linked will be changed to point to Quay, and new release images will not be pushed to Dockerhub.

**Comment by fedepaol** [comment]
> ~is multiarch fixed on quay? #1216~
> 
> seems to be the case

Yes, this was triggered mostly by the frr folks that are migrating everything to quay (which was not the case before, where the images on quay were semi-official)

**Pull request merged**
