### PR TITLE
Update dockerfiles to build with latest golang patch

### PR DESCRIPTION
**Pull request by mjnagel**
This is a small PR to keep up to date with the latest patch version of golang in the dockerfiles. 

The .9 and .10 versions have security fixes for CVEs that may show up in scans of this image (specifically https://github.com/golang/go/issues/63417)
- https://github.com/golang/go/issues?q=milestone%3AGo1.20.9+label%3ACherryPickApproved
- https://github.com/golang/go/issues?q=milestone%3AGo1.20.10+label%3ACherryPickApproved

### CODE REVIEW

**Comment by mjnagel** [comment]
I'd also be happy to make a PR to update the go.mod file - there's a decent amount of dependabot PRs that are pending but if it makes it easier I could combine them into one update PR - https://github.com/metallb/metallb/pulls/app%2Fdependabot

**Comment by fedepaol** [comment]
> I'd also be happy to make a PR to update the go.mod file - there's a decent amount of dependabot PRs that are pending but if it makes it easier I could combine them into one update PR - https://github.com/metallb/metallb/pulls/app%2Fdependabot

yup, the most challenging one being updating to the latest k8s / controller-runtime. I'd be happy if you can contribute that :-)

**Comment by fedepaol** [comment]
LGTM

**Comment by oribon** [comment]
hey @mjnagel are you still interested in working on that k8s/mod bump? if not I don't mind doing it myself

**Comment by mjnagel** [comment]
@oribon I haven't gotten around to it yet so feel free to tackle, definitely don't want to hold it up.

**Pull request merged**
