### PR TITLE
update frr to 8.5.2

### LINKED ISSUE #1241: frr-reloader fails: vtysh (frr): line 4: % Command incomplete: domainname
Using metallb 0.12.1, with kubernetes 1.23.3, using minimal changes to  `manifests/example-config.yaml` and `manifest/metallb-frr.yaml`, reloader fails:

```
PID is: 60, writing to /etc/frr_reloader/reloader.pid
Caught SIGHUP and acquired lock! Reloading FRR..
Checking the configuration file syntax
/usr/lib/frr/frr-reload.py:805: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if line is not "exit-vrf":
2022-02-27 00:01:35,231  INFO: Called via "Namespace(bindir='/usr/bin', confdir='/etc/frr', daemon='', debug=False, filename='/etc/frr_reloader/frr.conf', input=None, log_level='info', overwrite=False, pathspace=None, reload=False, rundir='/var/run/frr', stdout=True, test=True, vty_socket=None)"
2022-02-27 00:01:35,232  INFO: Loading Config object from file /etc/frr_reloader/frr.conf
2022-02-27 00:01:35,531  INFO: Loading Config object from vtysh show running
line 4: % Command incomplete: domainname

Traceback (most recent call last):
  File "/usr/lib/frr/frr-reload.py", line 1390, in <module>
    running.load_from_show_running(args.daemon)
  File "/usr/lib/frr/frr-reload.py", line 270, in load_from_show_running
    config_text = self.vtysh.mark_show_run(daemon)
  File "/usr/lib/frr/frr-reload.py", line 162, in mark_show_run
    raise VtyshException('vtysh (mark running-config) exited with status %d'
__main__.VtyshException: vtysh (mark running-config) exited with status 4
Syntax error spotted: aborting..
```
to make a functional config I had to make a few changes: (just enumerating here for replication purposes)

`metallb-frr.yaml` changes: (for arm compatibilty and version pinning)
* `image: quay.io/frrouting/frr:stable_7.5` --> `image: frrouting/frr:v7.5.1`
* `image: quay.io/metallb/speaker:main` --> `image: quay.io/metallb/speaker:v0.12.1`

`example-config.yaml` changes (bear minimum to get accepted by controller and start reloading):
```
39d38
<       bfdProfile: "bfdProfile1"
42c41
<       ebgp-multihop: true
---
>       ebgp-multihop: false
50,58d48
<       node-selectors:
<       - # Match by label=value
<         match-labels:
<           kubernetes.io/hostname: prod-01
<         # Match by 'key OP values' expressions
<         match-expressions:
<         - key: beta.kubernetes.io/arch
<           operator: In
<           values: [amd64, arm]
```

### PR DESCRIPTION
**Pull request by si458**
Thanks for sending a pull request! A few things before we get started:

1. If this is your first time, please read the [contributing guide](https://metallb.universe.tf/community/#contributing)
2. For non-trivial pull requests, please [file an
   issue](https://github.com/metallb/metallb/issues/new) first, and get
   agreement that the change is a good idea, and a general guideline
   for how it should be implemented, before sending code. Large PRs
   that weren't first discussed and agreed upon in an issue won't be
   accepted.
3. If the PR fixes a particular bug, please include the words "Fixed
   #<issue number>" in the PR text, so that the bug auto-closes when
   the PR is merged.

Fixed #1241

### CODE REVIEW

**Comment by fedepaol** [comment]
Last time I checked, 8.4.2 was the stable version suggested by the FRR maintainers.
Let me ask them again if this is good to pick.

**Comment by si458** [comment]
> Last time I checked, 8.4.2 was the stable version suggested by the FRR maintainers.
> Let me ask them again if this is good to pick.

Sure no worries, as suggested in a few posts I've found.
An update to at least 8.5.1 was needed to fix a few issues and include patches

**Comment by fedepaol** [comment]
> > Fair enough! Would you mind squashing all the commits to a single "upgrade FRR to 8.5.2" one?
> 
> Erm... not sure how to do that sorry? Any pointers?

https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together

**Comment by fedepaol** [comment]
(and thanks for filing this!)

**Comment by si458** [comment]
#2051 👍

**Pull request closed without merging**
