### PR TITLE
gh-pages: Add empty circleci configuration

### PR DESCRIPTION
**Pull request by russellb**
Add an empty circleci configuration to this branch to avoid circleci
reporting failures against this branch.

### CODE REVIEW

**Comment by fedepaol** [comment]
@russellb I think the right approach is to share the same circle-ci config and configure the filters to skip this branch:

https://github.com/metallb/metallb/blob/a33d307960a6288bb464f8da6b9959d6e83e4a60/.circleci/config.yml#L107
https://circleci.com/docs/2.0/configuration-reference/#branches

**Comment by russellb** [comment]
OK finally ... that took way longer than it should have.  I blame lack of coffee.

Now circleci won't report failures against this branch due to lack of config.  The current config makes it run nothing.  I noticed this on #963.  cc @gclawes

**Comment by russellb** [comment]
> @russellb I think the right approach is to share the same circle-ci config and configure the filters to skip this branch:
> 
> https://github.com/metallb/metallb/blob/a33d307960a6288bb464f8da6b9959d6e83e4a60/.circleci/config.yml#L107
> 
> https://circleci.com/docs/2.0/configuration-reference/#branches

yeah, could do that, but there's nothing to automatically keep them in sync, so i'm not sure there's much value in doing that.  It just puts a much more complicated (and eventually outdated) config in this branch with jobs that will never run.  I agree that would work though ...

**Comment by fedepaol** [comment]
Makes sense.
LGTM

**Comment by russellb** [comment]
thanks for the review!  Since this is just a trivial CI change to add a job that should never run, i'm just going to merge this :)

**Pull request merged**
