### PR TITLE
update install website to set kustomize ref to v0.9.3 - sync with metallb version

### PR DESCRIPTION
**Pull request by curx**
Thanks for sending a pull request! A few things before we get started:

1. If this is your first time, please read the [contributing guide](https://metallb.universe.tf/community/#contributing)
... done

2. For non-trivial pull requests, please [file an
   issue](https://github.com/google/metallb/issues/new) first, and get
   agreement that the change is a good idea, and a general guideline
   for how it should be implemented, before sending code. Large PRs
   that weren't first discussed and agreed upon in an issue won't be
   accepted.
... trivial

3. If the PR fixes a particular bug, please include the words "Fixed
   #<issue number>" in the PR text, so that the bug auto-closes when
   the PR is merged.
... not a bug

### CODE REVIEW

**Comment by caboteria** [comment]
LGTM @rata

**Comment by russellb** [comment]
should file a follow-up bug if release automation doesn't already know how to update this automatically

**Comment by rata** [comment]
It is already fixed the release atumation here: https://github.com/metallb/metallb/commit/eb450ff71009da423ffd65b24baff8f8e86514fc. Thanks for catching! :)

**Comment by rata** [comment]
@curx thanks a lot for the PR! It will be live in the website in a few minutes :)

**Pull request merged**
