### PR TITLE
dev-env: Create vtysh.conf

### LINKED ISSUE #713: FRR: Can't open configuration file
Running `docker exec frr vtysh -c "show ip bgp summary"` following https://github.com/metallb/metallb/tree/main/dev-env/bgp#bgp-test-env gives me the following:

```
% Can't open configuration file /etc/frr/vtysh.conf due to 'No such file or directory'.

IPv4 Unicast Summary:
BGP router identifier 172.18.0.5, local AS number 64512 vrf-id 0
BGP table version 2
RIB entries 0, using 0 bytes of memory
Peers 3, using 43 KiB of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt
172.18.0.2      4      64512       118       116        0    0    0 00:57:24            0        0
172.18.0.3      4      64512       118       116        0    0    0 00:57:24            0        0
172.18.0.4      4      64512       118       116        0    0    0 00:57:24            0        0

Total number of neighbors 3
```

As can be seen, the expected output is still shown so FRR seems to function correctly, however when trying to understand how the FRR-based environment worked I saw the error above and thought there was a problem. I think we should either get rid of this error or document that it's fine to see it.

```
# docker exec frr vtysh -c "show ver"
% Can't open configuration file /etc/frr/vtysh.conf due to 'No such file or directory'.
FRRouting 7.5-dev_git (eafeb84d9006).
Copyright 1996-2005 Kunihiro Ishiguro, et al.
configured with:
    '--prefix=/usr' '--sbindir=/usr/lib/frr' '--sysconfdir=/etc/frr' '--libdir=/usr/lib' '--localstatedir=/var/run/frr' '--enable-systemd=no' '--enable-rpki' '--enable-vtysh' '--enable-multipath=64' '--enable-vty-group=frrvty' '--enable-user=frr' '--enable-group=frr' 'CC=gcc' 'CXX=g++'
```

### PR DESCRIPTION
**Pull request by russellb**
Prior to this change, every time you ran the `vtysh` command in the
`frr` container when using the bgp dev environment, you would get an
error about `vtysh.conf` missing.  The error is misleading and makes
it seem like something is wrong.

Create an empty config file to suppress this error message.

Closes #713

### CODE REVIEW

**Comment by russellb** [comment]
The CI result is weird.  The deploy jobs should not be running on PRs and they aren't running against other PRs.  I wonder if it's somehow related to having circleci configured on my fork?

**Comment by russellb** [comment]
It looks like my circleci config change pushed in the last commit was not used in the last run.  I still don't know why the jobs are running at all, but this should at least get them to exit cleanly early if it does run.

**Comment by champtar** [comment]
when you configure circle CI on the main repo and on your fork behavior is weird

**Comment by russellb** [comment]
This is rebased and should be ok now

**Review by johananl — APPROVED** [review]
LGTM

**Comment by russellb** [comment]
I'm still confused about why the publish CI jobs are running here and not other CI jobs.  The only thing I can figure is that it's somehow confused by me having CircleCI configured against my personal fork of metallb, as well.  In any case, the changes include this PR make it safe to run those jobs against PRs.  They'll just exit early.

**Pull request merged**
