### PR TITLE
Set default prometheus port to 7472 for speakers

### PR DESCRIPTION
**Pull request by champtar**
This is the value used in the manifests

### CODE REVIEW

**Comment by russellb** [comment]
@champtar check out the commit I added to your branch and see if you're OK with it.  I'd like to start capturing release notes along the way to make release time a little bit easier.

**Comment by champtar** [comment]
Love it, LGTM

**Review by rata — APPROVED** [review]
LGTM, thanks!

**Comment by rata** [comment]
Merging. I'm not cherry-picking to 0.9 on purpose, this is a breaking change

**Comment by rata** [comment]
@champtar  @russellb thanks!

**Pull request merged**
