### PR TITLE
Use go-kit log.NewStdlibAdapter instead of our own adapter

### PR DESCRIPTION
**Pull request by champtar**
New log looks like:
{"caller":"net.go:785","component":"MemberList","msg":"[DEBUG] memberlist: Initiating push/pull sync with: 10.11.12.13:7946","ts":"2020-04-17T00:31:37.51568936Z"}

### CODE REVIEW

**Comment by champtar** [comment]
@rata this PR was tested ;)

**Comment by rata** [comment]
@champtar thanks! I guess the `caller` field is not very useful? Is it the file in the memberlist code?

Can you please add in the commit message too how the output looked before this patch too?

Other than that, LGTM :)

**Comment by champtar** [comment]
caller is the file/line in the memberlist code yes (`StdlibAdapter` is doing some parsing), I can remove it (`golog.Lshortfile`)
I'll add the previous output to the commit log

**Comment by rata** [comment]
Don't hesitate to ping me when ready :)

**Comment by champtar** [comment]
crazy week, I did lot of progress on many subjects, but not on MetalLB :(

**Comment by rata** [comment]
@champtar heh, it happens to all of us. Just wanted to make sure there wasn't a deadlock (you waiting for me, me waiting for you) :)

**Comment by champtar** [comment]
@rata done, please review and merge

**Pull request merged**
