### PR TITLE
Document the CNCF steps to add new maintainers

### PR DESCRIPTION
**Pull request by rata**
I've opened a PR to add fede to the CNCF/foundation repo: https://github.com/cncf/foundation/pull/258/files

And asked him to do the other steps I document in this PR.

Closes: #994

### CODE REVIEW

**Comment by rata** [comment]
cc @fedepaol

**Comment by rata** [comment]
@fedepaol Please merge if this LGTY :)

**Comment by fedepaol** [comment]
LGTM

**Comment by fedepaol** [comment]
Thanks!

**Comment by rata** [comment]
Cherry-picked into v0.11 and updated the live-website branch to reflect this too!

**Comment by rata** [comment]
Grr, in my local hugo renders fine, but on the server it doesn't. Will revert it in the v0.11 branch and try to fix it later :(

**Comment by rata** [comment]
Revert pushed here: https://github.com/metallb/metallb/commit/ab38fd3a9c51206f5b87f9fd1ffa09c55ecbf4cf

**Comment by rata** [comment]
This new PR indeed fixed the rendering issue, this is live now!

I cherry-picked this to branch v0.11 and live-website

**Pull request merged**
