### PR TITLE
Website: Add upgrade information

### PR DESCRIPTION
**Pull request by johananl**
Supersedes #583. Opened a new PR as I can't push changes to the old one.

I've incorporated the feedback from the old PR and improved the phrasing a bit. Comments are welcome.

### CODE REVIEW

**Comment by russellb** [comment]
lgtm

**Comment by russellb** [comment]
This PR will close issue #579

**Comment by rata** [comment]
Amended the commit so #573 is closed automatically :)

**Comment by rata** [comment]
The website is already updated with this change :)

**Pull request merged**
