### PR TITLE
Enabling pprof

### PR DESCRIPTION
**Pull request by shivamanipatil**
#1121 : Enabling Pprof for understanding the performance hits

### CODE REVIEW

**Comment by fedepaol** [comment]
I am gonna try this locally as soon as I can.
@shivamanipatil a couple of things:
- I see one linter error in CI to be taken care of
- can you adjust the commit message? A good guide to write commit messages can be found in our contributing guidelines: https://metallb.universe.tf/community/#commit-messages -> https://chris.beams.io/posts/git-commit/

**Comment by shivamanipatil** [comment]
Hey, @fedepaol  I have corrected the linter error and updated the commit message, hope the commit message is better now.

**Comment by fedepaol** [comment]
I tried it locally, it works.
Thanks @shivamanipatil for your contribution!

**Comment by fedepaol** [comment]
LGTM

**Pull request merged**
