### PR TITLE
E2E: Avoid BGP:FRR spec flakiness

### LINKED ISSUE #1196: E2E test flake: BGP session not established
The following test is failing in CI from time to time:

```
2022-01-23T07:59:46.9409730Z [90m------------------------------[0m
2022-01-23T07:59:46.9410365Z [0mBGP[0m [90mvalidate configuration changes[0m [0mconfigure peers one by one and validate FRR paired with nodes[0m 
2022-01-23T07:59:46.9410733Z   [1mIPV6[0m
2022-01-23T07:59:46.9411163Z   [37m/home/runner/work/metallb/metallb/e2etest/bgptests/bgp.go:841[0m
2022-01-23T07:59:46.9411426Z [BeforeEach] BGP
2022-01-23T07:59:46.9411889Z   /home/runner/go/pkg/mod/k8s.io/kubernetes@v1.20.2/test/e2e/framework/framework.go:174
2022-01-23T07:59:46.9412304Z [1mSTEP[0m: Creating a kubernetes client
2022-01-23T07:59:46.9412589Z Jan 23 07:59:46.933: INFO: >>> kubeConfig: /tmp/tmp02eyxd6g
2022-01-23T07:59:46.9412975Z [1mSTEP[0m: Building a namespace api object, basename bgp
2022-01-23T07:59:46.9470582Z Jan 23 07:59:46.946: INFO: Skipping waiting for service account
2022-01-23T07:59:46.9470886Z [BeforeEach] BGP
2022-01-23T07:59:46.9471243Z   /home/runner/work/metallb/metallb/e2etest/bgptests/bgp.go:94
2022-01-23T07:59:46.9471485Z [It] IPV6
2022-01-23T07:59:46.9471799Z   /home/runner/work/metallb/metallb/e2etest/bgptests/bgp.go:841
2022-01-23T07:59:46.9472219Z [1mSTEP[0m: configure peer
2022-01-23T07:59:51.9207138Z [1mSTEP[0m: checking all nodes are peered with the frr instance ebgp-multi-hop
2022-01-23T08:03:51.9723524Z Jan 23 08:03:51.972: FAIL: Timed out after 240.052s.
2022-01-23T08:03:51.9724125Z Expected
2022-01-23T08:03:51.9724646Z     <*errors.errorString | 0xc0007a9af0>: {
2022-01-23T08:03:51.9726004Z         s: "node fc00:f853:ccd:e793::2 BGP session not established",
2022-01-23T08:03:51.9726393Z     }
2022-01-23T08:03:51.9726676Z to be nil
2022-01-23T08:03:51.9807184Z 
2022-01-23T08:03:51.9807573Z Full Stack Trace
```

### PR DESCRIPTION
**Pull request by zeeke**
As explained [here](https://github.com/metallb/metallb/issues/1196#issuecomment-1026076150), the
`configure peers one by one and validate FRR paired with nodes` relies on BGP FRR peers to be reachable
by speaker nodes but the default configuration does not allow ipv6 traffic to be forwarded to the `multi-hop-net`.

Not sure this fix is clean enough or it's worth to refactor tests.

Fixed #1196

### CODE REVIEW

**Comment by fedepaol** [comment]
@zeeke mind explaining why this will fix the flake? I see that the test applies a new config right before doing the assertion, so it should not matter if we start from a clean state. What am I missing? https://github.com/metallb/metallb/blob/27fc90150c033e006dc5330bc427b509d938ae64/e2etest/bgptests/bgp.go#L831

**Comment by zeeke** [comment]
> @zeeke mind explaining why this will fix the flake? I see that the test applies a new config right before doing the assertion, so it should not matter if we start from a clean state. What am I missing?
> 
> https://github.com/metallb/metallb/blob/27fc90150c033e006dc5330bc427b509d938ae64/e2etest/bgptests/bgp.go#L831

The problem is with the FRR external peers configuration, not with the ConfigMap.

https://github.com/metallb/metallb/blob/27fc90150c033e006dc5330bc427b509d938ae64/e2etest/bgptests/bgp.go#L834

They are configured one by one, and the `multi-hop-net` network is not reachable via ipv6 if `ebgp-single-hop` has the default configuration (due top `no ipv6 forwarding` statement).

I'm going to add the following diagram somewhere in the code to help understanding the test network topology:

```
┌────────────────────────────────────────────────┐
│                  exec network                  │
│   ┌─────────┐                                  │
│   │         │                                  │
│   │ Speaker ├────┐       ┌─────────────────┐   │
│   │         │    │       │                 │   │
│   └─────────┘    │       │ ibgp-single-hop │   │
│                  │       │                 │   │
│   ┌─────────┐    │       └─────────────────┘   │
│   │         │    │                             │
│   │ Speaker ├────┤   ┌───────────────────────┐ │
│   │         │    │   │                       │ │
│   └─────────┘    │   │  ┌─────────────────┐  │ │
│                  │   │  │                 │  │ │
│   ┌─────────┐    ├───┼──┤ ebgp-single-hop │  │ │
│   │         │    │   │  │                 │  │ │
│   │ Speaker │    │   │  └───────┬─────────┘  │ │
│   │         ├────┘   │          │            │ │
│   └─────────┘        │          │            │ │
│                      │          │            │ │
└──────────────────────┼──────────┼────────────┼─┘
                       │          │            │
                       │  ┌───────┴────────┐   │
                       │  │                │   │
                       │  │ ibgp-multi-hop │   │
                       │  │                │   │
                       │  └───────┬────────┘   │
                       │          │            │
                       │  ┌───────┴────────┐   │
                       │  │                │   │
                       │  │ ebgp-multi-hop │   │
                       │  │                │   │
                       │  └────────────────┘   │
                       │     multi-hop-net     │
                       │     172.30.0.0/16     │
                       │fc00:f853:ccd:e798::/64│
                       └───────────────────────┘
```

**Comment by fedepaol** [comment]
> > @zeeke mind explaining why this will fix the flake? I see that the test applies a new config right before doing the assertion, so it should not matter if we start from a clean state. What am I missing?
> > https://github.com/metallb/metallb/blob/27fc90150c033e006dc5330bc427b509d938ae64/e2etest/bgptests/bgp.go#L831
> 
> The problem is with the FRR external peers configuration, not with the ConfigMap.
> 
> https://github.com/metallb/metallb/blob/27fc90150c033e006dc5330bc427b509d938ae64/e2etest/bgptests/bgp.go#L834
> 
> They are configured one by one, and the `multi-hop-net` network is not reachable via ipv6 if `ebgp-single-hop` has the default configuration (due top `no ipv6 forwarding` statement).
> 
> I'm going to add the following diagram somewhere in the code to help understanding the test network topology:
> 
> ```
> 
>   ┌────────────────────────────────────────────┐
>   │                exec network                │
>   │ ┌─────────┐                                │
>   │ │         │                                │
>   │ │ Speaker ├────┐      ┌─────────────────┐  │
>   │ │         │    │      │                 │  │
>   │ └─────────┘    │      │ ibgp-single-hop │  │
>   │                │      │                 │  │
>   │ ┌─────────┐    │      └─────────────────┘  │
>   │ │         │    │                           │
>   │ │ Speaker ├────┤   ┌───────────────────────┼──────────────────────────┐
>   │ │         │    │   │                       │                          │
>   │ └─────────┘    │   │  ┌─────────────────┐  │       ┌────────────────┐ │
>   │                │   │  │                 │  │       │                │ │
>   │ ┌─────────┐    ├───┼──┤ ebgp-single-hop ├──┼───────┤ ibgp-multi-hop │ │
>   │ │         │    │   │  │                 │  │       │                │ │
>   │ │ Speaker │    │   │  └─────────────────┘  │       └────────────────┘ │
>   │ │         ├────┘   │                       │                          │
>   │ └─────────┘        │                       │       ┌────────────────┐ │
>   │                    │                       │       │                │ │
>   └────────────────────┼───────────────────────┘       │ ebgp-multi-hop │ │
>                        │                               │                │ │
>                        │       multi-hop-net           └────────────────┘ │
>                        │       172.30.0.0/16                              │
>                        │  fc00:f853:ccd:e798::/64                         │
>                        └──────────────────────────────────────────────────┘
> ```

Can you add it (in a separate PR) as a README for the e2e tests? I think everyone will benefit from it.

**Comment by fedepaol** [comment]
Also, now I understand it.
LGTM

**Pull request merged**
