### PR TITLE
Doc: add BGP graceful restart section in the website

### LINKED ISSUE #2531: Add docs about BGP Graceful Restart
### Is your feature request related to a problem?

As BGP graceful restart support was added, it would be nice to have some docs about how to use, which problem solves etc

### Describe the solution you'd like

A section in the website under advaced config?

### Additional context

_No response_

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### PR DESCRIPTION
**Pull request by karampok**
/kind documentation

**What this PR does / why we need it**:
Fixes #2531

**Special notes for your reviewer**:

**Release note**:

```release-note
Help section for BGP Graceful Restart feature added
```

### CODE REVIEW

**Comment by fedepaol** [comment]
This is a bit too verbose.

Can we make this a small section on the advanced bgp configuration section where we:

- reference the rfc, stating that we are in the "shared fate" scenario
- say how to configure gr
- a note about usign it with bfd being implementation specific but ours works

**Comment by karampok** [comment]
> This is a bit too verbose.
>
> Can we make this a small section on the advanced bgp configuration section where we:
> 
> * reference the rfc, stating that we are in the "shared fate" scenario

I suppose you refer in the BFD, generally we are in the "not shared fate" between control/data plane

> * say how to configure gr
> * a note about usign it with bfd being implementation specific but ours works

Do you think it worth keeping the verbose version somewhere in the repo? maybe under design?

**Comment by fedepaol** [comment]
> Do you think it worth keeping the verbose version somewhere in the repo? maybe under design?

Yep let's add it as an addendum to the proposal

**Comment by karampok** [comment]
@fedepaol can we merge that? Thanks

**Pull request merged**
