### PR TITLE
Add Dockertest support

### PR DESCRIPTION
**Pull request by fedepaol**
In order to validate the correctness of the frr configuration files, we spin up a frr container and try to reload the file produced by the unit tests to ensure it's valid.

### CODE REVIEW

**Comment by oribon** [comment]
lgtm

**Comment by russellb** [comment]
How about adding a test case that feeds this check an intentionally invalid config file? That way we'll make sure the check fails properly, too.

**Comment by fedepaol** [comment]
> How about adding a test case that feeds this check an intentionally invalid config file? That way we'll make sure the check fails properly, too.

Added a wip commit for validation, but now that I read the comment again you are asking for something else.
Will work on it

**Comment by fedepaol** [comment]
@russellb flakes aside, I think I addressed your comment

**Comment by russellb** [comment]
> @russellb flakes aside, I think I addressed your comment

thanks

**Pull request merged**
