### PR TITLE
WIP E2E: Set external containers as passive

### PR DESCRIPTION
**Pull request by fedepaol**
Another step in our search for fixing the flakes, we set the external containers as passive.

### CODE REVIEW

**Comment by russellb** [comment]
lgtm

**Comment by msherif1234** [comment]
pls try to add more details here any side can/should be able to initiate TCP session why this is a restriction for CI ?

**Comment by fedepaol** [comment]
no wait, this was a wip PR as suggested in one of the debugging discussions. I should have marked this as WIP

**Comment by fedepaol** [comment]
We had a failing test in this PR, so I don't think there's a need to merge now.

**Pull request closed without merging**
