### PR TITLE
chart: add option to set speaker sidecar resources

### PR DESCRIPTION
**Pull request by chinnonae**
Add option to set speaker sidecar resources in helm chart (for these containers, frr, reloader, and frr-metrics)

### CODE REVIEW

**Comment by fedepaol** [comment]
Thanks!

**Comment by fedepaol** [comment]
Ehm, can you either squash the commits or provide context to the second commit on why did you regenerate them?

**Comment by chinnonae** [comment]
Okay, I've squashed the commits.

**Comment by fedepaol** [comment]
Thanks!

**Pull request merged**
