### PR TITLE
Disable metrics endpoint in controller-runtime

### LINKED ISSUE #1432: Speaker fails to start if port 8080 in use
With the switch to controller-runtime the speakers are now unable to start up if another process is bound to port 8080.

### PR DESCRIPTION
**Pull request by stefancoetzee-xneelo**
Disable the metrics endpoint in controller-runtime manager,
to allow start up on hosts that already use port 8080.
Fixed #1432

### CODE REVIEW

**Comment by fedepaol** [comment]
Ah, good catch!
I guess it's safe to disable them for now as we don't have any prom rule configured to listen.
We may choose to make it configurable when we start exporting them.

**Comment by fedepaol** [comment]
Also, would you mind extending the commit message with the reason of the change?

**Comment by fedepaol** [comment]
Sorry I wasn't clear. What I meant was the body of the commit.
We are trying to follow this guidelines for the commits: https://chris.beams.io/posts/git-commit/

**Comment by stefancoetzee-xneelo** [comment]
Sorry, haven't had enough coffee yet.

**Pull request merged**
