### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by moschlar**
Fix notice block about metallb-operator not being closed

### CODE REVIEW

**Comment by fedepaol** [comment]
Thanks! Mind signing the commit?

**Comment by moschlar** [comment]
> Thanks! Mind signing the commit?

I suppose there just is no way of doing that via the GitHub web interface, or am I too blind to find?
Anyways - gonna do it when I'm back home.

**Comment by fedepaol** [comment]
> > Thanks! Mind signing the commit?
> 
> I suppose there just is no way of doing that via the GitHub web interface, or am I too blind to find? Anyways - gonna do it when I'm back home.

Yep, you need to re-push the commit with the signed-off notation

**Comment by moschlar** [comment]
Signed-Off and Signed the commit :wink:

**Pull request merged**
