### PR TITLE
Remove unnecessary pinned deps, plus consistently pin to v0.20.2

### PR DESCRIPTION
**Pull request by fedepaol**
The dependencies introduced by pinning to k8s.io/kubernetes were using  mixed versions. Here we consistently pin them to 0.20.2.

Also, ran `go mod tidy`.
Fixes (or cleans a bit) https://github.com/metallb/metallb/issues/953

### CODE REVIEW

**Comment by fedepaol** [comment]
cc @rata

**Review by rata — APPROVED** [review]
LGTM, thanks!

**Comment by rata** [comment]
@fedepaol thanks! Thinking about it a little more, can you please also add a comment with the link in this issue comment (https://github.com/metallb/metallb/issues/953#issuecomment-921020803)? Just mentioning we need to do this replace madness due to importing k8s.io/kubernetes that is not supposed to be imported

**Comment by fedepaol** [comment]
> @fedepaol thanks! Thinking about it a little more, can you please also add a comment with the link in this issue comment ([#953 (comment)](https://github.com/metallb/metallb/issues/953#issuecomment-921020803))? Just mentioning we need to do this replace madness due to importing k8s.io/kubernetes that is not supposed to be imported

Sure, let me do that.

**Comment by fedepaol** [comment]
> > @fedepaol thanks! Thinking about it a little more, can you please also add a comment with the link in this issue comment ([#953 (comment)](https://github.com/metallb/metallb/issues/953#issuecomment-921020803))? Just mentioning we need to do this replace madness due to importing k8s.io/kubernetes that is not supposed to be imported
> 
> Sure, let me do that.

Done

**Comment by rata** [comment]
@fedepaol thanks! I'll wait for the CI and then merge :)

**Pull request merged**
