### PR TITLE
feat(chart): allow provisioning of IPAddressPools and L2/BGPAdvertisement CRs

### PR DESCRIPTION
**Pull request by tamcore**
This PR will introduce an `addresspools` parameter in `values.yaml`, which is similar as possible to the previous `configInline.address-pools` and will make it easier to quickly get up and running. It also briefly allows to distinguish, if it's supposed to be a Layer2 or BGP setup and will deploy the correct advertisement CR for it, while also being able to already use `nodeSelectors`.

More complicated setups will still required manual provisioning of the correct CRs.

### CODE REVIEW

**Comment by TamCore** [comment]
Done. Opened #1485 and removed the commit from and rebased this one.

**Comment by gclawes** [comment]
I don't think we should try to imitate the format of the original configmap in the helm chart, specifically the `protocol:` field.  If we're going to template resources, we should just provide different fields for different resource types (instead of trying to derive them from `.Values.addresspools` entries, maybe under `.Values.configs.*`.

This would mean separate `.Values.configs.bfdprofiles` `.Values.configs.bgpadvertisements` `.Values.configs.bgppeers` `.Values.configs.ipaddresspools` `.Values.configs.l2advertisements` `.Values.configs.communities`

**Comment by gurolakman** [comment]
hello, i noticed that this change in 0.13.3 apparently broke the installation script of osm [open source mano] rel 10.1.x. until now, osm has been making use of a configmap file as follows:

$ cat /etc/osm/docker/metallb-config.yaml 
configInline:
  address-pools:
   - name: default
     protocol: layer2
     addresses:
     - 10.34.24.8/32
configInline:
  address-pools:
   - name: default
     protocol: layer2
     addresses:
     - 10.34.24.8/32

and using this file during helm operations. 

$ helm repo add metallb https://metallb.github.io/metallb
$ helm repo update
$ helm install --create-namespace --namespace metallb-system metallb metallb/metallb -f /etc/osm/docker/metallb-config.yaml

per v0.13.3 release notes, i tried to convert this file to a cr as follows:

$ docker run -d -v $(pwd):/var/input quay.io/metallb/configmaptocrs -source /etc/osm/docker/metallb-config.yaml 

but this resulted in creation of an empty <resources.yaml> file.

-rw-r--r-- 1 root root   0 Jul  8 14:30 resources.yaml

did i do something wrong? if this were successful, i was hoping to use this file during the helm install procedure.

$ helm install --create-namespace --namespace metallb-system metallb metallb/metallb -f /etc/osm/docker/resources.yaml

as an alternate approach [and a possible workaround], i modified the osm installation script as follows:

$ helm install --create-namespace --namespace metallb-system metallb metallb/metallb -f /etc/osm/docker/metallb-config.yaml --version 0.13.2

while this alleviatated the Error: INSTALLATION FAILED: execution error at (metallb/templates/deprecated_configInline.yaml:2:4): Starting from v0.13.0 configInline is no longer supported. Please see https://metallb.universe.tf/#backward-compatibility, osm installation was not fully successful.

any suggestions? thanks in advance!

**Comment by gurolakman** [comment]
i'm attaching a copy of the original configmap file since the format of it seems to be messed up above. it'll be great if someone can convert it to a format acceptable to metallb release 0.13.3. many thanks in advance!
[metallb-config.yaml.txt](https://github.com/metallb/metallb/files/9075130/metallb-config.yaml.txt)

**Comment by fedepaol** [comment]
> i'm attaching a copy of the original configmap file since the format of it seems to be messed up above. it'll be great if someone can convert it to a format acceptable to metallb release 0.13.3. many thanks in advance! [metallb-config.yaml.txt](https://github.com/metallb/metallb/files/9075130/metallb-config.yaml.txt)

Please file an issue and don't pollute the discussion over this PR, I'll reply there

**Comment by arukiidou** [comment]
please update values.schema.json
for example

```
    "configs": {
      "description": "MetalLB crd configuration",
      "type": "object",
      "properties": {
        "ipaddresspools": { 
          "description": "IPAddressPool",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "addresses": { 
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "autoAssign": { "type": "boolean" },
              "avoidBuggyIPs": { "type": "boolean" }
            },
            "required": [
              "name",
              "addresses"
            ]
          }
        }
      }
    },
```

**Comment by sam-sre** [comment]
How was this issue solved? I'm still getting the error `"Starting from v0.13.0 configInline is no longer supported. Please see https://metallb.universe.tf/#backward-compatibility\"` when using Helm charts to configure MetalLB
I am automating my Helm with Ansible with the following Values.yaml file


```
configInline:
  address-pools:
   - name: default
     protocol: layer2
     addresses:
     - <address range>

**Comment by arukiidou** [comment]
In most cases, you just do

https://github.com/metallb/metallb/blob/main/configsamples/simple_pool_adv_l2.yaml

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.0/24
  - 192.168.9.1-192.168.9.5
  - fc00:f853:0ccd:e799::/124
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
```

**Comment by sam-sre** [comment]
> In most cases, you just do
> 
> https://github.com/metallb/metallb/blob/main/configsamples/simple_pool_adv_l2.yaml
> 
> ```
> apiVersion: metallb.io/v1beta1
> kind: IPAddressPool
> metadata:
>   name: example
>   namespace: metallb-system
> spec:
>   addresses:
>   - 192.168.10.0/24
>   - 192.168.9.1-192.168.9.5
>   - fc00:f853:0ccd:e799::/124
> ---
> apiVersion: metallb.io/v1beta1
> kind: L2Advertisement
> metadata:
>   name: empty
>   namespace: metallb-system
> ```

Thanks for the quick response.
The issue is how to translate those new CRDs to Helm template/Values.yaml files
The replacement of `Configinline` is not clear in the official MetaLB site..

**Comment by luk43** [comment]
Hi everyone,

This issue got closed, because of inactivity.
Would it still be possible to merge this or what needs to be done for that?

Thanks in advance!

**Pull request closed without merging**
